"""
Base strategy class and strategy registry.
All trading strategies inherit from BaseStrategy.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Optional

import pandas as pd


class SignalType(Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    EXIT = "EXIT"


@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    signal_type: SignalType
    symbol: str
    exchange: str
    entry_price: float
    stop_loss: float
    target: float
    quantity: int
    strategy_name: str
    confidence: float  # 0.0 to 1.0
    reason: str
    timestamp: datetime = None
    metadata: dict = None

    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()
        if self.metadata is None:
            self.metadata = {}

    @property
    def risk_reward_ratio(self) -> float:
        risk = abs(self.entry_price - self.stop_loss)
        reward = abs(self.target - self.entry_price)
        return reward / risk if risk > 0 else 0


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies."""

    def __init__(self, name: str, config: dict):
        self.name = name
        self.config = config
        self.is_active = True

    @abstractmethod
    def generate_signals(self, market_data: dict) -> list[Signal]:
        """
        Analyze market data and generate trading signals.
        
        Args:
            market_data: Dict containing relevant data (OHLCV, indicators, etc.)
            
        Returns:
            List of Signal objects (can be empty if no opportunities)
        """
        pass

    @abstractmethod
    def should_exit(self, position: dict, current_data: dict) -> Optional[Signal]:
        """
        Check if an existing position should be exited.
        
        Args:
            position: Current position details
            current_data: Latest market data
            
        Returns:
            Exit Signal if should exit, None otherwise
        """
        pass

    def activate(self):
        self.is_active = True

    def deactivate(self):
        self.is_active = False
